name: audio_book
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  audio_service: ^0.18.12
  audio_video_progress_bar: ^2.0.1
  bloc: ^8.1.3
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  just_audio: ^0.9.36
  # on_audio_query: ^2.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/books/
    - assets/json/
